# Generated by Django 4.1.7 on 2023-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_name', models.CharField(max_length=100)),
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
